-- CLIENTES E SEUS PEDIDOS
SELECT DISTINCT 
	   CONCAT(C.NOME,' ',C.SOBRENOME) NOME_COMPLETO,
       I.DESCRICAO PEDIDO,
       I.VALOR_TOTAL TOTAL_PEDIDO,
       P.DESCRICAO DESCRICAO_PRODUTO,
       P.CATEGORIA CATEGORIA_PRODUTO
  FROM PRODUTO P,
	   PEDIDO_ITEM PI,
       CLIENTE C,
       PEDIDO I
 WHERE C.ID = I.CLIENTE_ID
   AND PI.PEDIDO_ID = I.ID
   AND P.ID = PI.PRODUTO_ID
 ORDER BY NOME_COMPLETO;
--
-- NUMERO DE PEDIDOS POR CLIENTE
SELECT COUNT(I.ID) NUM_PEDIDO,
       CONCAT(C.NOME,' ',C.SOBRENOME) NOME_COMPLETO
  FROM CLIENTE C,
       PEDIDO I
 WHERE C.ID = I.CLIENTE_ID
GROUP BY NOME_COMPLETO;
--
-- ESTOQUE DE CADA PRODUTO
SELECT I.DESCRICAO,
       SUM(E.QUANTIDADE)
  FROM PRODUTO_ESTOQUE E,
       PRODUTO I
 WHERE E.PRODUTO_ID = I.ID
 GROUP BY I.DESCRICAO;
--
-- QUANTIDADE QUE CADA VENDEDOR VENDEU E SUA COMISSAO
SELECT I.DESCRICAO,
	   ROUND(SUM(P.PRECO_UNITARIO * PV.QUANTIDADE), 2) VALOR_VENDIDO,
       ROUND(SUM(((P.PRECO_UNITARIO * PV.QUANTIDADE) * I.COMISSAO) / 100), 2) COMISSAO_SOBRE_VENDAS
  FROM PRODUTO P,
       PRODUTO_VENDEDOR PV,
       VENDEDOR I
 WHERE PV.VENDEDOR_ID = I.ID
   AND P.ID = PV.PRODUTO_ID
 GROUP BY I.DESCRICAO;
--
-- LISTA DE FORNECEDORES E SEUS ESTOQUE POR PRODUTO
SELECT F.DESCRICAO FORNECEDOR,
	   I.DESCRICAO PRODUTO_DESCRICAO,
       E.QUANTIDADE,
       I.CATEGORIA
  FROM FORNECEDOR F,
       PRODUTO_FORNECEDOR E,
       PRODUTO I
 WHERE E.PRODUTO_ID = I.ID
   AND F.ID = E.FORNECEDOR_ID;